NCL-6876 Add support for semantic-version-plugin
project-ncl/gradle-manipulator pull request #354
Opened 2021-12-22 09:33 UTC by rnc

2022-01-10 19:12 UTC, dwalluck requested changes

2022-01-10 19:13 UTC, dwalluck commented on cli/src/test/java/org/jboss/gm/cli/SemanticPluginTest.java
> +        Git.cloneRepository()
I mean the use of JGIt, but since it requires the GIT metadata, I can see why after discussion.

2022-01-10 19:53 UTC, rnc commented on cli/src/test/java/org/jboss/gm/cli/SemanticPluginTest.java
> +        Git.cloneRepository()
Yeah, seemed to easier to clone it to be honest.

2022-01-10 19:55 UTC, rnc commented on common/src/main/java/org/jboss/gm/common/utils/PluginUtils.java
> +        SUPPORTED_PLUGINS.put(SEMANTIC_BUILD_VERSIONING, "preRelease");
I agree, but as thats a wider change for the pluginRemoval functionality I'm tempted to argue to move that to another ticket?

2022-01-10 19:56 UTC, rnc commented on common/src/main/java/org/jboss/gm/common/utils/PluginUtils.java
> +    public static void pluginRemoval(Logger logger, String[] pluginRemoval, File t)
Agreed, will make the change to the argument naming tomorrow.

In NCLSUP-523 I'm changing pluginRemoval to take a Set<String>.

2022-01-12 07:51 UTC, rnc commented
I have made the change to the API parameters as suggested. As I need to move this forward and there are other PRs blocked on this, I'm merging this.

2022-01-12 07:51 UTC, merged